### ISSUE TITLE
Adjustable font size ?

### ISSUE THREAD

**Issue by aroberge** [mrodalgaard/atom-todo-show#102]
Is it possible to adjust the font size ... and, if not, could this be made a configurable parameter?

**Comment by mrodalgaard** [comment]
Would you mind posting a screenshot? Is the font size too small or too big?

You can play around with the following in your custom styles.less (`Application: Open Your Stylesheet`):

```
.show-todo-preview {
  font-size: 8px;
}
```

**Comment by aroberge** [comment]
The solution to modify the Stylesheet works for me.   The font was too small for my old eyes...
