### ISSUE TITLE
When followed by something doesn't match

### ISSUE THREAD

**Issue by DanielRamosAcosta** [mrodalgaard/atom-todo-show#103]
In the [Google Coding Style Guide](https://google.github.io/styleguide/cppguide.html#TODO_Comments) says to type TODOs with some identifier like:

    // TODO(someone): Description

But this isn't catched...

**Comment by mrodalgaard** [comment]
This sounds reasonable, and hopefully pretty easy to add. Thank you, I'll have a look at this.

**Comment by mrodalgaard** [comment]
Will be included in next release.
