### ISSUE TITLE
Separate inline TODOs

### ISSUE THREAD

**Issue by willnwhite** [mrodalgaard/atom-todo-show#105]
Here's a TODO with a TODO inside it. I think it would be better to put this (inline) TODO into its own entry.
![separate inline todos](https://cloud.githubusercontent.com/assets/8081877/13841178/2dccb8e6-ec1f-11e5-941a-d6b1c065159c.png)

**Comment by mrodalgaard** [comment]
Hi @willnwhite; I think it is a terrible anti-pattern to have multiple todos in one line. It would require a second scan of every todo match to support this (edge case) and will thereby not be added. But thank you for the feedback.
