### ISSUE TITLE
XXX.

### ISSUE THREAD

**Issue by christianbrodbeck** [mrodalgaard/atom-todo-show#107]
Hi there,

Thanks for this useful extension!

I noticed that todos followed immediately buy punctuation other than colon are not included by default (as in, "The result of this test was XXX.") and was wondering whether that was intentional. I use Atom with markdown so it's probably a non-standard case. However I think it could be easily included by inserting `|[,.;]` into the default regex (`/\b(${TODOS}):?\d*($|\[,.;]|\s.*$)/g`) unless that has other consequences I did not think of.

**Comment by mrodalgaard** [comment]
I think this is a valid request. I have added `:;.,`, which will be included in next release. In your case it will show up as "No details", since it reads the content after the todo. I am working on a solution for this, where in this case it reads the content before.

**Comment by christianbrodbeck** [comment]
That's great, thanks!
