### ISSUE TITLE
Find in project search on all open projects

### ISSUE THREAD

**Issue by keul** [mrodalgaard/atom-todo-show#110]
I'm a little confused by the "Todo Show: find in project" behavior.

What I'm expecting by this feature is a search for TODOs inside the current project (to be honest I'm not sure how to define an Atom project as "current") but it seems its looking inside *every* project in the workspace.
This is a problem because I've 20+ projects.

I'm wondering if is possible to limit the "find in project" feature to only a specific project, or for example to all the open project in the tree view.

Apart of that: a very useful plugin. Kudos

**Comment by mrodalgaard** [comment]
You are right, it does not handle multiple projects that well, it scans the whole workspace. I think adding a a 4th scope option would be suitable (so it'll become Workspace, Project, Open Files, Active File).
