### ISSUE TITLE
Multiple Projects Conflict

### ISSUE THREAD

**Issue by morbidgames** [mrodalgaard/atom-todo-show#112]
I have 4 project folders open in Atom and when I click on a `TODO` item, it opens up a non-existing file (with no contents) from the first project only.

The issue is that it can't recognize which project folder contains the file with the `TODO` tag in it.

**Comment by mrodalgaard** [comment]
Stupid mistake. Thank you for reporting.

**Comment by morbidgames** [comment]
Great to hear it's resolved. I'll update. And no problem at all.

**Comment by mrodalgaard** [comment]
I'll update the package later when I have looked at the other tickets.

**Comment by morbidgames** [comment]
Can you please let me know when you do? I would appreciate it.

**Comment by mrodalgaard** [comment]
@morbidgames; version `1.6.0` is pushed now.

**Comment by morbidgames** [comment]
Thank you
