### ISSUE TITLE
@todo (JSDoc)

### ISSUE THREAD

**Issue by onury** [mrodalgaard/atom-todo-show#118]
It should find [`@todo`](http://usejsdoc.org/tags-todo.html) tags by default, which is a valid JSDoc tag/directive.

Nice work, btw.

**Comment by mrodalgaard** [comment]
Hi @onury, thank you for the feedback.

I'm using the same tags as Atoms bundled package [language-todo](https://github.com/atom/language-todo) and I think that hits the broader audience. If you haven't already done so, you can add your tag (lowercase `todo`) to the `findTheseTodos` configuration. It should find tags with `@` in front as well.

**Comment by onury** [comment]
Thanks @mrodalgaard. That works.
