### ISSUE TITLE
ignore ctags file by default

### ISSUE THREAD

**Issue by mpathy** [mrodalgaard/atom-todo-show#119]
You should ignore a ctags file by default because it is a massive file - which, when it contains TODO or other lines, they are only a duplicate of those in the sourcecode with no additional meaning.

It slows down Atom or maybe even crashes it, if one accidentally makes a click on it in the TODO list.

(btw how can I manually ignore a single file instead of a folder?)

**Comment by mrodalgaard** [comment]
Do you mean the `ctag` files without any file extension? That seems reasonable, but shouldn't it already be added to `.gitignore`? Unless of course you are looking at a project not under source control (shame on you 😃).

Currently there is no way to ignore a folder or file in a specific projet not under git (and I do not think I will ever implement this, as it is certainly an edge case). But you can still add the file or folder to your `ignoreThesePaths`.

To ignore a single file with `ignoreThesePaths` you use the same syntax as [.gitignore](https://git-scm.com/docs/gitignore), e.g. `**/ignore_this_file.txt`.

**Comment by mrodalgaard** [comment]
I think adding the file type to your `ignoreThesePaths` or `.gitignore` is the best solution for you. I will close this issue.
