### ISSUE TITLE
Find in Workspace in packages menu is shown incorrectly

### ISSUE THREAD

**Issue by AmirTugi** [mrodalgaard/atom-todo-show#120]
Packages -> Todo-Show -> Find in Worksp**ae**
![image](https://cloud.githubusercontent.com/assets/8065975/15670949/b6602ad4-2730-11e6-9514-56bab8a28f64.png)

**Comment by mrodalgaard** [comment]
This is already fixed in 146f1cee704572871dc205e29ec1b38624141858 and will be included in next release. Thank you.
