### ISSUE TITLE
Doesn't show TODOs in project while showing in open files

### ISSUE THREAD

**Issue by mannyhenri** [mrodalgaard/atom-todo-show#121]
When I search a project it shows nothing even if there are a few TODO in the project. However when I select open files and the file in question is opened, it shows the TODO. 

![screen shot 2016-06-04 at 9 37 39 am](https://cloud.githubusercontent.com/assets/8015930/15799834/32a08f76-2a38-11e6-912f-01c6786d1ad3.png)
![screen shot 2016-06-04 at 9 37 48 am](https://cloud.githubusercontent.com/assets/8015930/15799833/329d1616-2a38-11e6-994c-f3c101f48cf7.png)

**Comment by mrodalgaard** [comment]
Are you sure the file is saved inside the currently opened workspace / project? I am unable to reproduce this, but if I save a file outside the workspace, I see the same behaviour which is expected.

You say you have several todos in the project but none of them are shown? Are you able to send the project (or a similar example) that I can reproduce this issue on?

**Comment by mannyhenri** [comment]
closing no longer an issue
