### ISSUE TITLE
how do I tag a todo item

### ISSUE THREAD

**Issue by russellharrower** [mrodalgaard/atom-todo-show#126]
Hi i am a noob at using your plugin but here is my todo`
  // TODO: SETTINGS - code | tpl and php for settings`

what I would like to do is TAG this Settings

**Comment by seanbuscay** [comment]
Hi @russellharrower 

The short answer is to use a hash and then the tag word.  From what I can tell, it works when putting it after the todo description, so in your example above, it would look like:

`// TODO: SETTINGS - code | tpl and php for settings #settings`

I'll try to add some other examples in a follow-up comment.

**Comment by mrodalgaard** [comment]
@seanbuscay thank you for answering. You are absolutely right. I have added a description to the README.
