### ISSUE TITLE
Default Ignore not working for bower_components

### ISSUE THREAD

**Issue by atodicebear** [mrodalgaard/atom-todo-show#129]
Hey,
The Title says it allready.
Clean Install of todo-show and searching in /Workspace/Project/OpenFiles and it shows bower_components? But Excluding default node_modules is working.
Have I something to add in ignore that bower_components is out?

Additions:
.gitignore
node_modules
public
.tmp
.sass-cache
.idea
client/bower_components
dist
/server/config/local.env.js
npm-debug.log
coverage
todo show ignore 
*_/node_modules/, *_/vendor/, *_/client/bower_components/, *_/bower_components/

Windows User

Thx for help :)

**Comment by Navrin** [comment]
If you're on windows, change the '/' to '\' in the paths.

**Comment by onetrev** [comment]
Just to clarify for any Windows users because in the above tip the backslash is missing. Your ignore settings should look something like this:
`**\node_modules\, **\vendor\, **\bower_components\`

**Comment by mrodalgaard** [comment]
Can I close this? Does it work as expected on Bill Gates' OS?

**Comment by onetrev** [comment]
Yes, definitely can close it I would say. If one follows my tips above for Windows OS, it works exactly as expected.

**Comment by mrodalgaard** [comment]
Thank you @onetrev

**Comment by CKLFP** [comment]
I don't think that's the problem... I had the same issue I'm on Windows 10 and with a fresh instalation (force to do so :(  )  every thing Works fine now and I didn't change the slashes.
I do think is a conflict with another package... no idea witch on.
But what ever Works right? :) Thanks.
