### ISSUE TITLE
Moving the TODO panel in the bottom area triggers weird behaviours

### ISSUE THREAD

**Issue by nesk** [mrodalgaard/atom-todo-show#130]
[I'm talking about this behaviour.](https://youtu.be/z7mC70pkDn8) I don't really know if this is due to your plugin or if it's an issue with Atom.

**Comment by mrodalgaard** [comment]
This could potentially be caused by the package trying to remember the panes flex-grow. Try to disable the "Remember View Size" in the *todo-show* settings.

**Comment by nesk** [comment]
This worked like a charm. 👌 Thank you!
