### ISSUE TITLE
keywords not highlighted in typescript

### ISSUE THREAD

**Issue by cortopy** [mrodalgaard/atom-todo-show#131]
In JS files, I get the keywords highlighted no matter what. However, in typescript this doesn't happen for single line comments. TODOs still appear in my list though.

```
  /**
   *   TODO will be highlighted
   */

  // TODO won't be highlighted
```

**Comment by mrodalgaard** [comment]
Hi @cortopy, in-code highlight of TODO text is handled by [Atoms own language-todo package](https://github.com/atom/language-todo). This package is only responsible for fetching TODOs project-wide and listing them nicely to the user.

**Comment by cortopy** [comment]
thanks  @mrodalgaard 
submitted at https://github.com/atom/language-todo/issues/48
