### ISSUE TITLE
Ignoring Path not working

### ISSUE THREAD

**Issue by atodicebear** [mrodalgaard/atom-todo-show#132]
Whats wrong?:
Searching in Workspace/Project shows bower_components results as well.
In settings:
ignoreThesePaths: [' ** /node_modules/', ' ** /vendor/', '** /bower_components/'] //that were the defaults
ive added as extra to test
[**/node_modules/, **/vendor/, **/client/bower_components/, **/bower_components/, **/client/app/bower_components/]
it is still not working.
But the package works in General. Finding my Todos and Ignoring node_modules, except bower_components.

Solutions?

Thx for Help :)

**Comment by mrodalgaard** [comment]
Hi @atodicebear, is this a duplicate of #129?

**Comment by atodicebear** [comment]
Oh yes :/
Still any solutions maybe? 
Im sorry for that and closing
