### ISSUE TITLE
atom crash when term3 tab is opened.

### ISSUE THREAD

**Issue by wangyun** [mrodalgaard/atom-todo-show#133]
If other package like term3 tab is opened. When I use todo-show, atom will crash.

**Comment by mrodalgaard** [comment]
Hi @wangyun, this apparently is a known bug in [term3](https://github.com/Floobits/atom-term3) when splitting panes, see [HERE](https://github.com/Floobits/atom-term3/issues/67). It also happens if you use `Markdown Preview: Toggle` and more.

**Comment by wangyun** [comment]
Thanks @mrodalgaard , I can comfirm that like you said, this crash is related to term3, it happens if doing split pane when term3 tab is opened and not the current active tab.
