### ISSUE TITLE
Autosave TODO's to a .txt or .md file

### ISSUE THREAD

**Issue by pedro-c** [mrodalgaard/atom-todo-show#135]

**Comment by mrodalgaard** [comment]
The save todos isn't enough (upper right corner icon and right click menu)? Would you then set a file path and update the file each time a scan is done? How would you handle multiple projects with a saved todo file each? A path relative to the project?

**Comment by pedro-c** [comment]
Yes, every time the scan was done it would update the file. A file for each project in the root of the project would be perfect ! 👍 thanks for replying :)

**Comment by mrodalgaard** [comment]
Hi @pedro-c, so I do not think this is a feature that a lot of people are looking for. So I rather not add an extra config until multiple people ask for this feature or similar.

I have made a quick workaround solution for you. Put the code from below into your `init.coffee` file and it'll save a `todos.md` file in your open project each time a scan by todo-show is made:

```
atom.packages.onDidActivatePackage (pack) ->
  if pack.name is "todo-show"
    fs = require 'fs'
    path = require 'path'

    pack.mainModule.collection.onDidFinishSearch ->
      filePath = path.join(pack.mainModule.collection.getActiveProject(), "todos.md")
      fs.writeFileSync(filePath, pack.mainModule.collection.getMarkdown())
```

Tell me how it works out.

**Comment by sompylasar** [comment]
Related https://github.com/mrodalgaard/atom-todo-show/issues/144
