### ISSUE TITLE
don't search for TODOs in VCS ignored paths

### ISSUE THREAD

**Issue by xh3b4sd** [mrodalgaard/atom-todo-show#138]
I found your package and I love it. I was only wondering why I see TODOs of dependencies my project is using. This is my current list to ignore, which will further grow. It is very tedious to maintain that and with a new project new dependencies come in and I need to adapt this. I would be fine if the paths included in the VCS ignored paths would be added here automatically. In case of git this would mean to respect the content of `.gitignore`. 

```
**/node_modules/, **/vendor/, **/bower_components/, **/.workspace/, **/.gobuild/, **/.atom/, **/dotfiles/, **/.vim/ 
```

Do I maybe do something wrong here?

**Comment by mrodalgaard** [comment]
If you open an Atom workspace that is under git source control, it should pick up the `.gitignore` file as described in the [readme](https://github.com/mrodalgaard/atom-todo-show#configuration):

> An array of files / folders to exclude (syntax according to scandal used internally by Atom). 
⚬ globally: Ignored Names from atom core settings. 
⚬ locally: Ignores anything in your .gitignore file if the current project is a valid git repository and atom core setting Exclude VCS Ignored Paths is checked.

If this is not the case for you, then we need to further investigate in your project settings.
