### ISSUE TITLE
Enhancement: Make filetypes configurable

### ISSUE THREAD

**Issue by mischah** [mrodalgaard/atom-todo-show#139]
Hi, this is a very useful package 💖 

Making the filestypes configurable would be a nice enhancement.
That way I could limit the shown Todos to for example `*.js` files.

**Comment by mrodalgaard** [comment]
Hi @mischah, why do you need to only look for todos inside specific file types? Are you really looking for a way to ignore some file types? It would be possible to add a global todo-show config that specifies which files are you want to look in, but I do not think it would be very useful?

**Comment by mischah** [comment]
The use case:
I’m the JS guy and I don’t wanna see the ToDos of the CSS guy 😏

**Comment by mrodalgaard** [comment]
Hi @mischah. I played around with some solutions for this, but did not end up with anything that felt right. Best solution for you is to ignore the file types that you are not interested in (just as you would with `.gitignore`). E.g. by adding `*.css, *.scss, *.less` to your todo-show `ignoreThesePaths` config. I know this is not the best solution, but I consider your issue as kind of an edge case.

**Comment by mischah** [comment]
Thanks for the feedback.
