### ISSUE TITLE
Configure keyboard shortcut

### ISSUE THREAD

**Issue by jarvelov** [mrodalgaard/atom-todo-show#140]
I would like to configure the keyboard shortcut to toggle the todo-show tab as it conflicts with that of another package. Can this option be provided in the package's settings? As of now I've edited the source but this would be overwritten if the package is updated (I presume).

**Comment by mrodalgaard** [comment]
The feature of remapping keyboard shortcuts comes standard with Atom. Go to Settings > Keybindings > and search for todo-show. Use the copy icon and paste it into `your keymap file`. Then edit it to your needs (you might have the use `unset!` on the old binding).

**Comment by jarvelov** [comment]
Hey, that's really neat! Thanks, I didn't know that!
