### ISSUE TITLE
Setting: Save Output As === List seems to have no effect ?

### ISSUE THREAD

**Issue by honkskillet** [mrodalgaard/atom-todo-show#141]
I apologize in advance if I'm not understanding what this setting should do.

Whether I set this setting to List or Table the generated output in the Todo Show window is alway a table.  I'd prefer the output to be a List (similar to the old TodoReview output in Sublime Text).

**Comment by sompylasar** [comment]
@honkskillet This setting is not about the Todo Show window itself, but about the "Save Todos to File" output (the cloud button on the right of the Todo Show window). Do you see the same output in the generated file?

**Comment by mrodalgaard** [comment]
As @sompylasar mentions; this is regarding the saved output, not the shown pane.

saveOutputAs = 'Table': (Markdown table)
```
| Text | Line | Path |
|--------------------|
| Test") | _:63_ | [spec/todo-view-spec.coffee](spec/todo-view-spec.coffee) |
| Use a *." | _:278_ | [spec/todo-model-spec.coffee](spec/todo-model-spec.coffee) |
```

saveOutputAs = 'List': (Markdown list)
```
- Test") _:63_ [spec/todo-view-spec.coffee](spec/todo-view-spec.coffee)
- Use a *." _:278_ [spec/todo-model-spec.coffee](spec/todo-model-spec.coffee)
```

I believe it is working as expected.
