### ISSUE TITLE
Setting for lowercase included

### ISSUE THREAD

**Issue by gabrielkunkel** [mrodalgaard/atom-todo-show#143]
I've been used to working in WebStorm and when I add a TODO, I can usually skip the shift key. It will find a

``` javascript
// todo: eat a plate of spaghetti
```

just as easily as it can find

``` javascript
// TODO: eat a plate of spaghetti
```

So, I have a bunch of code that *atom-todo-show* won't work with. I'm sure there are ways to deal with this in the config, but that's less convenient for new adopters. My basic proposal is to add a checkbox in settings where lowercase versions of "todo," "xxx," etc. will be recognized.

I'm volunteering to add this feature. Would this be of interest to anyone else? What does @mrodalgaard say?

Thanks. ...And thanks, again.

**Comment by mrodalgaard** [comment]
This seems like a reasonable proposal. I'm not a huge fan of too many settings, but this would be helpfull and people have been asking for this feature before. A `boolean` config (include lower case todos) that is default off.

I do not have that much free time at the moment to add features, so a PR is very welcome, @gabrielkunkel.

**Comment by WadeShuler** [comment]
I also think this should be added. Following phpDoc, they use lowercase `@todo`. I simply added `todo` to the end of the "Find These Todos" list in the settings.

    TODO, FIXME, CHANGED, XXX, IDEA, HACK, NOTE, REVIEW, NB, BUG, QUESTION, COMBAK, TEMP, todo

**Comment by mrodalgaard** [comment]
You can solve this by adding a `i` to the default regex to make it case insensitive: `/\b(${TODOS})[:;.,]?\d*($|\s.*$|[\{\[\(].+$)/gi` or as @WadeShuler did; add the specific string to `FindTheseTodos`.

The default of this package should only hit the most common todos. My stand is that it should find the same as the bundled package [language-todo](https://github.com/atom/language-todo), then the package can be extended to hit whatever the specific user needs.
