### ISSUE TITLE
Remember "What to search" option 

### ISSUE THREAD

**Issue by giovazz89** [mrodalgaard/atom-todo-show#147]
Add a settings option to remember the last "What to search" value: it will enable defaults different than "Workspace", based on the user routine

**Comment by Phoenixalibur** [comment]
This can be partially fixed with custom keymapping, but the enhancement should still be made for clicking on the status bar indicator icon.

**Comment by mrodalgaard** [comment]
The default keymapping now toggles the todo view instead of specifically searching in workspace. And the the status bar icon know also toggles. Thank you for the feedback.
