### ISSUE TITLE
**/vendor/ path

### ISSUE THREAD

**Issue by CKLFP** [mrodalgaard/atom-todo-show#149]
Hi, I don't really know if this is an issue with the package or some bad config. from my side, but **/vendor/ path is in the ignore path list, but when I perform a search in project all TODOS in vendor path are shown.
Why is this happen and how to fix this.

Thanks.

**Comment by mrodalgaard** [comment]
Are you on Windows? See https://github.com/mrodalgaard/atom-todo-show/issues/129

I am still looking into a cross-platform solution for this.

**Comment by stephen-last** [comment]
@mrodalgaard For now, maybe you could add something to the settings field, a note for Windows users to change the direction of the slashes.

Just starting using this BTW, it's very helpful - so thanks!

**Comment by CKLFP** [comment]
Windows 10 and all of a sudden every thing works fin now.
