### ISSUE TITLE
Duplicated tabs create depends on the direction of ToDo show

### ISSUE THREAD

**Issue by moriyas1984** [mrodalgaard/atom-todo-show#150]
I found that  a new tab creates on the right of the tab of the target file when I click a todo item to jump to the line where the original text is written. In that case, the cursor is on the first line of the file so I cannot see the original text.
It seems to occurs when "Open List In Direction" is set to "down".
If the configuration is set to "left", "right" or "on top", no additional tab creates and the cursor jumps to a correct line.
If it is set to "up", a new duplicated tab creates on the right of the todo tab but the cursor jumps to a correct line in the new tab. 

It may be due to my environment, but I would like you to confirm and fix it not to create unnecessary tabs if possible.

Regards :)

**Comment by mrodalgaard** [comment]
I fixed some situations where tabs where opened in the wrong place. Though I believe 4ea532fb38aa825cc193b888da3575351d184522 is actually fixing what you are observing, where the view is not correctly centering on the found todo. This will be included in next release.
