### ISSUE TITLE
Over Multiple Lines

### ISSUE THREAD

**Issue by dhope0000** [mrodalgaard/atom-todo-show#151]
If i lay my todo's out in the following format 

```
// TODO { 'title': 'hello', 
// 'body': 'blah blash blah blah',
// 'labels': 'Foo, bar' 
// }
```

Is there a regular expresion I can use to parse them?

**Comment by mrodalgaard** [comment]
This is going to be really hard to implement right. Parsing multiple line todos has been an open ticket since 2014 #13, and I have not yet seen anything close to a solution. I will close this as a duplicate, but thank you for the feedback.
