### ISSUE TITLE
Option to list todos in current branch

### ISSUE THREAD

**Issue by dakl** [mrodalgaard/atom-todo-show#154]
This looks very useful. I would like to be able to list TODOs only in files that have been changed in the current branch, vs for example master. Currently I run `git diff --name-only master|xargs grep TODO` on the command line to check it.

**Comment by mrodalgaard** [comment]
Thank you for the feedback. I think this is too much of an _edge case_ to add as a feature. If more people are interested in something similar I will take a look again.
