### ISSUE TITLE
Have "Refresh on Save" Config Option

### ISSUE THREAD

**Issue by nnadeau** [mrodalgaard/atom-todo-show#156]
While keeping the `Todo Show` list current is important, the refresh time is significant with large projects. More specifically, the list is currently set to refresh on saves, which is an issue for obsessive `ctrl+s` people like me.

A potential solution would be to allow the user to optionally disable the `refresh on save` feature and opt for manual refreshes.

**Comment by steronydh** [comment]
Good idea, or it could re-scan just the saved file(s) only.
