### ISSUE TITLE
Is it impossible to search for **DO**?

### ISSUE THREAD

**Issue by joquk** [mrodalgaard/atom-todo-show#158]
I use "**DO**" as my usual todo note string of choice.

I think your system doesn't allow Asterix.

I tried \*\*DO\*\* And that also fails.

**Comment by mrodalgaard** [comment]
The `findTheseTodos` values are put into the `findUsingRegex` regular expression before being used to search your workspace. Therefor you need to escape the special characters (like asterisks).

I actually saw some strange behaviour when using asterisks before the `findTheseTodos` objects. Nothing seemed to work (`\u002A`, `\\*`, `\\\\*`, etc.). So I think the following is your best bet at this point. It works by only looking at an asterisk behind your keyword.

`"DO\\*"`

**Comment by joquk** [comment]
Sorry for the late response,

I really appreciate your response however and will give that a go!

Thank you


Matthew Waite
matthew@joq.com
