### ISSUE TITLE
Three Pane when I open it down

### ISSUE THREAD

**Issue by IvanTC95** [mrodalgaard/atom-todo-show#160]
First of all, sorry for my English.

Well, this is the problem -> http://prntscr.com/fftxb9

When I open the TODO Pane down in the window, it create other empty pane... How could I fix it?

**Comment by mrodalgaard** [comment]
Hi, PR #162 should fix this once it gets accepted. It puts the whole todo view in the new Atom Dock.

**Comment by mrodalgaard** [comment]
#162 is released now!
