### ISSUE TITLE
Add TODO pane in dock

### ISSUE THREAD

**Issue by davidbarredo** [mrodalgaard/atom-todo-show#161]
The new dock feature in atom is awesome, have you consider implementing it?

**Comment by mrodalgaard** [comment]
I am working on it already. But time is precious. If I push it to a branch I would very much like you to try it out.

**Comment by davidbarredo** [comment]
Sure, just let me know how to do it and I'll be glad to help 😉

**Comment by mrodalgaard** [comment]
Hi @davidbarredo; take a look at #162. The info on how to load the package is in the description. 

Open different projects, update, change, move the dock around, etc. and let med know how it works. I still am looking into making the view more compact and modern.

**Comment by davidbarredo** [comment]
Everything looks fine 👍 

I'm a big fan of the compact views, I've made some minor changes in your styles and the TODO pane looks like this:
<img width="413" alt="screen shot 2017-06-12 at 10 13 07" src="https://user-images.githubusercontent.com/657206/27025605-66a8b034-4f5b-11e7-8be6-a840559748f0.png">

- font-size reduced
- padding reduced
- for _span_ and _a_ inside the _td_:
  - max-height
  - overflow scroll 

Also, take into account, not everybody love compact views, so maybe it worth it to add a check in the package configuration to enable/disable it.

I'll keep testing the branch for a while.

**Comment by davidbarredo** [comment]
Tested also with atom 1.18.0 and everything is working as expected, even the TODO tab with the new Git and GitHub tabs in the right dock.

@mrodalgaard do you want the snippet with the "compact view" styles?

**Comment by mrodalgaard** [comment]
@davidbarredo, thank you for the feedback and testing. #162 is merged to master now and will make a major release soon.
