### ISSUE TITLE
Ignore There Paths seems unable handle the Path start with `#`

### ISSUE THREAD

**Issue by bitliuxm** [mrodalgaard/atom-todo-show#166]
I have a folder #test which I want to ignore.
I try to use both `#test`  and  `\#test`.
but seems not working.

**Comment by mrodalgaard** [comment]
todo-show uses [workspace.scan](https://atom.io/docs/api/v1.19.2/Workspace#instance-scan)'s exclude regex option (also used in [find-and-replace](https://github.com/atom/find-and-replace)). Maybe it does not support hashtags in directories?

I also think using hashtag or other symbols in file or directory names is an anti-pattern.
