### ISSUE TITLE
TODOS only colored if in /**/ in js

### ISSUE THREAD

**Issue by KudMath** [mrodalgaard/atom-todo-show#168]
TODOS are not color coded if behind // type comment, only when in /* */ comments.
See picture.
![screen capture](https://user-images.githubusercontent.com/3056289/27920602-6ed2d302-6275-11e7-914e-eed457eeddab.png)

**Comment by davidbarredo** [comment]
Those comments are coloured by your installed syntax theme, the https://github.com/atom/language-todo package adds the syntax for it. 

But the TODO package has nothing to do with it.

With the TODO package and my syntax theme I'm seeing them coloured:
<img width="262" alt="screen shot 2017-07-20 at 10 19 48" src="https://user-images.githubusercontent.com/657206/28409444-ffde9942-6d3a-11e7-97b0-021d59d30fa5.png">

**Comment by KudMath** [comment]
Ok, thanks for the answer. What syntax theme are you using?

**Comment by davidbarredo** [comment]
I'm using my own: https://atom.io/packages/atom-monokai-dark-syntax
