### ISSUE TITLE
link broken error 500

### ISSUE THREAD

**Issue by fusco** [mrodalgaard/atom-todo-show#171]
Updating to “todo-show@2.0.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/todo-show/versions/2.0.0/tarball: 500

**Comment by voxpelli** [comment]
The update has worked for me when I did it earlier today, have you tried updating again?

A `500` indicates that an internal server error happened at the server when trying to fetch and such errors are often temporary glitches within a server

**Comment by mrodalgaard** [comment]
Your update was interrupted. As @voxpelli mentions - try again.
