### ISSUE TITLE
Line Highlighting

### ISSUE THREAD

**Issue by round** [mrodalgaard/atom-todo-show#173]
Just a thought, but perhaps each type could highlight the entire line. I've done a very hacky stylesheet-only implementation of this together using only pseudoclasses:

```
.syntax--todo, .syntax--fixme {
  background: rgba(0,255,0,.05);
  display: inline-block;
  position: relative;
  color:  rgba(0,255,0,.5);
  font-weight: bold;
  &:before, &:after {
    position: absolute;
    display: block;
    content: '';
    top: 0;
    z-index: 999;
    height: 100%;
    width: 1024px;
    background: inherit;
    pointer-events: none;
    z-index: 9999;
  }
  &:before {
    right: 100%;
    content: '';
    text-align: right;
  }
  &:after {
    left: 100%;
  }
}

.syntax--fixme {
  color: rgba(255,0,0,1);
  background: rgba(255,0,0,.1);
}
```

Ends up looking like this:
![screen shot 2017-09-13 at 1 59 35 am](https://user-images.githubusercontent.com/2340336/30361860-40c23d80-9827-11e7-9fa7-e77d92f6c053.png)

This is, of course, an enhancement, and not a bug :) thanks for the great package! It's essential to my daily workflow.

**Comment by mrodalgaard** [comment]
See #174; I like the idea, but this is an enhancement for [language-todo](https://github.com/atom/language-todo). Also maybe this could be implemented as a theme.
