### ISSUE TITLE
Setting custom Todo types does not work in Atom Beta

### ISSUE THREAD

**Issue by round** [mrodalgaard/atom-todo-show#174]
Not sure if this is beta-specific, but setting these:

![screen shot 2017-09-13 at 2 02 33 am](https://user-images.githubusercontent.com/2340336/30361955-a1ca1da0-9827-11e7-9765-1639d4c93544.png)

does not seem to actually highlight them in the editor. Only the defaults continue to be highlighted –
 but the new custom items do save (Atom returns no errors).

Running Atom 1.21.0-beta0 on MacOS 10.13 High Sierra Beta (17A360a)

**Comment by keul** [comment]
Same for me on Atom 1.12.0

I configured the field as `TODO, XXX, BBB, FIXME` but `BBB` is ignored

**Comment by mrodalgaard** [comment]
People, people; this package searches for todos. For todo word highlighting see [language-todo](https://github.com/atom/language-todo). You guys are not the first to make this mistake, so I have added an attention to this package's readme e080089dd64fd072d9e6d495276e3ff08206113b as it was not very clear from the text.
