### ISSUE TITLE
Shortcut not working on ubuntu-based systems

### ISSUE THREAD

**Issue by CeroProgramming** [mrodalgaard/atom-todo-show#176]
Strg Alt T opens the terminal on ubuntu-based systems instead of accessing to the plugin so it's necessary to use the command promt with Strg Shift P. Is there a way to use the shortcut?

Sorry for my bad english :)

**Comment by mrodalgaard** [comment]
I know. That is why the default todo-show shortcut on Ubuntu is <kbd>ALT + SHIFT + T</kbd> and not <kbd>CTRL + SHIFT + T</kbd> as on a Mac.
