### ISSUE TITLE
Trying to make todo-show start when atom starts

### ISSUE THREAD

**Issue by db1996** [mrodalgaard/atom-todo-show#178]
i saw [this post](https://discuss.atom.io/t/todo-show-package-auto-run-on-startup/37614) so i tried that but i'm getting the error below when i start atom:

[Enter steps to reproduce:]

1. install todo-show
2. paste " # Activate Todo-Show
atom.commands.dispatch(document.querySelector('atom-workspace'), 'todo-show:find-in-workspace')" in your init.coffee

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [todo-show](https://github.com/mrodalgaard/atom-todo-show) package 2.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'search' of undefined

```
At C:\Users\Old-PC1\.atom\packages\todo-show\lib\todo-show.js:54

TypeError: Cannot read property 'search' of undefined
    at setTimeout (/packages/todo-show/lib/todo-show.js:54:26)
```

### Commands

```
     -0:16.1.0 todo-show:find-in-workspace (atom-workspace.workspace.scrollbars-visible-always)
     -0:16.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
advanced-open-file 0.16.7 
atom-elixir 0.2.3 
auto-indent 0.5.0 
blade-snippets 0.2.0 
emmet 2.4.3 
file-icons 2.1.12 
ftp-remote-edit 0.12.3 
goto-definition 1.3.4 
language-blade 0.36.0 
minimap 4.29.7 
minimap-quick-highlight 1.0.1 
quick-file-actions 0.2.1 
quick-highlight 0.11.0 
sync-settings 0.8.3 
todo-show 2.1.0 
```

**Comment by mrodalgaard** [comment]
Seems to work fine here, but I am also on Mac OSX. I would however recommend just using the keyboard shortcut to trigger the todo-show package when you need it (<kbd>ALT</kbd> + <kbd>SHIFT</kbd> + <kbd>T</kbd>).
