### ISSUE TITLE
keep results current

### ISSUE THREAD

**Issue by Bengt** [mrodalgaard/atom-todo-show#18]
It is tedious to start TODO-show manually and close older versions after each change. Please keep the "TODO-show Results" pane current when open.

**Comment by benhinchley** [comment]
:+1: +1 for this
Would make it much easier to keep a track of current todos/fixmes etc

**Comment by MRodalgaard** [comment]
Commit 48660eaf15617c965172b9b67538c368b360bf00 added a refresh button in the upper right corner. Plus the key shortcut and palette command now toggles the list for a quick look.

The way I normally use todo lists is by opening them to get a quick overview, jumping to the todo I'm interesting in, then toggling the list closed again. Until I figure out a _not-cpu-intensive_ way of constantly scaning all changes for the configured regexes, this will have to do.

**Comment by Wotanhaecker** [comment]
It would be nice that it would do an auto-refresh too, because usually i work with this panel opened. But i can understand that it's technically not that easy to implement- although there could be a way to keep track of changing files in the atom core...

**Comment by mrodalgaard** [comment]
Auto update on save is included in new release.
