### ISSUE TITLE
Add local .gitignore paths to Ignored Paths

### ISSUE THREAD

**Issue by bhgomes** [mrodalgaard/atom-todo-show#180]
This should be an option instead of manually writing it every time. At least there could be a way of custom ignored paths for each project.

**Comment by mrodalgaard** [comment]
Hi @bhgomes, that is exactly what the package already does. I have just tested it. Adding a project folder to `.gitignore` removes it from the searched scope of todos. Adding a project folder to `IgnoreThesePaths` does the same.
