### ISSUE TITLE
Enable prioritization of certain tasks 

### ISSUE THREAD

**Issue by JulienMasgonty** [mrodalgaard/atom-todo-show#181]
Hi,
Not really a bug but more of a suggestion : 
It would be great, in my opinion, to have the possibility to add some sort of criticality indicator to certain tasks in my list (maybe a color indicator, an icon or whatever)

Currently i have to read all my tasks and determine which one i should do first, so i think this would be a great time saver

If this is already an existing functionnality and i just didn't see it, please excuse me for the unnecessary issue

But anyway it's a great tool, thanks for your work

**Comment by JulienMasgonty** [comment]
nevermind, i just realized i could simply use the tags system to do this

**Comment by mrodalgaard** [comment]
Yes. I think tags are the way to go here.
