### ISSUE TITLE
Excluding directories or choose from path within project

### ISSUE THREAD

**Issue by muuvmuuv** [mrodalgaard/atom-todo-show#186]
It would be great, if I could select where in my Project todo-show is searching. So it wont take so long to find all todos/fixme etc (I have a full Joomla/Wordpress in most Projects). Maybe todo-show is searching for a config file (.todorc) at the beginning or something like that.

**Comment by mrodalgaard** [comment]
You can right click the directory or file you want to the search in the right side file tree view. Select `Search for Todos` and the todo pane will show (type set to 'custom' and scope set to the relative path you selected).

A config is probably a little overkill. But it might be an idea to extend this so you can change the scope afterwards by typing it. I just do not have a good enough idea on how this would look like.
