### ISSUE TITLE
Show todos in bottom panel like linter plugin

### ISSUE THREAD

**Issue by isavl** [mrodalgaard/atom-todo-show#187]
Just idea have option in settings for show todos in right pane or in bottom pane like do it linter plugin.

**Comment by mrodalgaard** [comment]
This is already supported. You can drag the todo tab from the right panel to the bottom panel just like https://github.com/steelbrain/linter, and it will open there next time as well.

**Comment by isavl** [comment]
Wow, but how? I cant drag panels.
Atom version 1.25.0-beta2.

**Comment by mrodalgaard** [comment]
You just drag the todo tab to where you want it. See below graphic.

![untitled](https://user-images.githubusercontent.com/659763/36634898-31fa73e2-19ac-11e8-9200-2a8a39518a94.gif)

**Comment by isavl** [comment]
Aaaaah I have disabled tab plugin this because i can't drag. Now all ok. Thank you very much.
