### ISSUE TITLE
AtomEnvironment.showSaveDialogSync is deprecated.

### ISSUE THREAD

**Issue by robertrossmann** [mrodalgaard/atom-todo-show#188]
Atom 1.25-beta.0 introduced async dialog boxes and deprecated their sync counterparts. See the [release notes](https://github.com/atom/atom/pull/16245). This appears when I attempt to save the TODO list to a file.

atom.showSaveDialogSync is deprecated and will be removed soon.
      Please, implement ::saveAs and ::getSaveDialogOptions instead for pane items
      or use Pane::saveItemAs for programmatic saving.
```
AtomEnvironment.showSaveDialogSync (<embedded>:1434:11)
ShowTodoView.saveAs (/Users/robert/.atom/packages/todo-show/lib/todo-view.coffee:370:33)
HTMLButtonElement.<anonymous> (/Users/robert/.atom/packages/todo-show/lib/todo-view.coffee:3:59)
HTMLButtonElement.dispatch (/Users/robert/.atom/packages/build/node_modules/jquery/dist/jquery.js:4435:9)
HTMLButtonElement.elemData.handle (/Users/robert/.atom/packages/build/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by mrodalgaard** [comment]
Since it is only a deprecation warning, I will have a look at this when Atom 1.25 is out of beta.

**Comment by barabah** [comment]
atom.showSaveDialogSync is deprecated and will be removed soon. Please, implement ::saveAs and ::getSaveDialogOptions instead for pane items or use Pane::saveItemAs for programmatic saving.
