### ISSUE TITLE
No TODO lists are saved.

### ISSUE THREAD

**Issue by spilix** [mrodalgaard/atom-todo-show#189]
Unfortunately, no TODO lists are saved when you click on save the current list.
Atom 1.24 x64 Linux Version / Manjaro Linux / Deepin desktop environment
todo-show 2.2.0

**Comment by pu3antasyah** [comment]
Todo also can't find and listed todo comment that I've writted in some code files.

Linux

**Comment by mrodalgaard** [comment]
@spilix; Please try after updating to newest version (todo-show 2.3.0), which exports the todos in markdown to a new text editor without saving.

**Comment by chuckplantain** [comment]
It looks like this fails on 'active file' scope. Maybe because the active file gets changed to the untitled file during the process. I had to use 'worlspace' scope and then parse out the file I am interested.
version: todo-show@2.3.0

**Comment by aubreyz** [comment]
Still same here (as per @chuckplantain above). Only possible to export whole project or workspace, not just the active file. 

Markdown output is a bit fiddly to parse. csv would be a useful addition if possible - the Table output could be adapted to do that

(the table output doesn't render as valid markdown -- for example does not display in markdown-preview-plus) - I think the second line of the output is incorrect.)
