### ISSUE TITLE
I can't download the todo list

### ISSUE THREAD

**Issue by asanchezml** [mrodalgaard/atom-todo-show#195]

**Comment by mrodalgaard** [comment]
Please try after updating to newest version (todo-show 2.3.0), which exports the todos in markdown to a new text editor without saving.

**Comment by asanchezml** [comment]
Works to me as you say, but I can't see the lines in the file in which the TODOs are, so people can't check them out when I share the file. Could you add them to the Markdown file?

**Comment by mrodalgaard** [comment]
The exported markdown attributes match the ones you are showing in your todo list. So to add lines to the output you simple have to add the `Line` attribute to your `ShowInTable` config.
