### ISSUE TITLE
Get the actual TODO list

### ISSUE THREAD

**Issue by Supalien** [mrodalgaard/atom-todo-show#197]
usualy TODO lists are like this:

"""
TODO:
fix bugs
add features
"""

and not like this:
#TODO:
#fix bugs
#add features

so try to detect the whole string that the TODO is in, instead of only the line that it's in.

**Comment by mrodalgaard** [comment]
This is not a todo list package. This package is meant for picking up the todos in your code, where you normally put a todo line before or to the right of a code line.
