### ISSUE TITLE
BUG: New todo keywords not colored

### ISSUE THREAD

**Issue by dsanalytics** [mrodalgaard/atom-todo-show#199]
Hi, if I add new keywords in Find Todos box like COMEBACK they are recognized and listed, but they not colored in code. There's no crash or errors reported, just they are ignored for coloring. It'd be great if that could be corrected - thanks in advance.

OS: Win10 64bit
Atom: 1.23.2 x64

P.S. Thanks for the great plugin

**Comment by mrodalgaard** [comment]
As mentioned in the README:

Attention: This package searches for todos. For todo word highlighting see [language-todo](https://github.com/atom/language-todo).
