### ISSUE TITLE
Range value may be wrong.

### ISSUE THREAD

**Issue by munierujp** [mrodalgaard/atom-todo-show#207]
![2019-02-19 10 27 30](https://user-images.githubusercontent.com/20086673/52984027-fed5a680-3430-11e9-85b0-a0764a5d0494.png)

Please see above image.

Line is `3`, but Range is `2,3,2,10`.
In English, is "range" zero-based number?

---

in `todo-model.coffee`, `line` is maked by adding `1` to `range`.

```coffee
# Make sure range is serialized to produce correct rendered format
match.position = [[0,0]] unless match.position and match.position.length > 0
if match.position.serialize
  match.range = match.position.serialize().toString()
else
  match.range = match.position.toString()
```

```coffee
match.line = (parseInt(match.range.split(',')[0]) + 1).toString()
```

**Comment by mrodalgaard** [comment]
Yes, range is zero based and is the raw value received from Atoms `atom.workspace.scan`.

**Comment by munierujp** [comment]
I see😄
