### ISSUE TITLE
Allow option to hide regex in todo view.

### ISSUE THREAD

**Issue by Mixerman123** [mrodalgaard/atom-todo-show#80]
Allowing the option to hide the regex in the actual TODO bar would declutter the view. There is no reason while viewing your todo's that you should have to see the messy regex next to it, this is only something that users would want to see in the settings. Some users may like to see it, so adding the option pleases all.

Just a suggestion, thanks for this awesome addon thing :D

**Comment by mrodalgaard** [comment]
I agree. I am working on moving the whole list to a table instead, where the user could potentially edit which columns should be visible and sorted by. Please hang on... :smile:

**Comment by mrodalgaard** [comment]
New release includes a table where you can set which data should be shown (click the little gear icon).
