### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by urecio** [mrodalgaard/atom-todo-show#81]
In order to organise better the TODOS, would be nice to tag them, for instance: 
`//TODO: get user avatar. #profile`
Then there could be another option on the todo-show menu, like: "Search todos by tag"

**Comment by mrodalgaard** [comment]
This is actually a very good idea.

Once I get the time to move the todo list to a flexible html table, I will add this as an optional column.

**Comment by urecio** [comment]
I'm happy to help with this if you tell me a bit more about your idea. AFAIF they are already in a table, are you planning to allow the user to sort them?

**Comment by mrodalgaard** [comment]
@urecio; thank you, but it is a big refactoring of the code base, improving and changing a lot of things.

You can look at #85 for progress and if you want to give it an early spin it would help a lot with some feedback.

Once that PR is merged I will start putting new features in.

**Comment by mrodalgaard** [comment]
I have added the optional tag column to the todo table. Give it a spin.

**Comment by urecio** [comment]
Absolutely brilliant! Great work @mrodalgaard. thanks!

**Comment by urecio** [comment]
Not sure if I should configure something else, but on html TODOS, tags don't work. 
Example: `<!-- TODO: Fix this link. #bug. -->`

**Comment by mrodalgaard** [comment]
@urecio; Last sunday I made some internal improvements where this was fixed. I have just published a new version that takes care of this. Thank you for bringing this to my attention.

**Comment by urecio** [comment]
Great! thank you!

**Comment by mffap** [comment]
Is there a way to also add custom comment 'delimiters'? I have the issue that tags are not recognized for Laravel's blate templates that uses something different: 
`{{-- TODO: Fix this link. #bug. --}}`

For other comments (like in the HTML example above) this works just fine. Thanks.
