### ISSUE TITLE
trash in title

### ISSUE THREAD

**Issue by akaRem** [mrodalgaard/atom-todo-show#84]
<img width="658" alt="2015-11-21 20 44 31" src="https://cloud.githubusercontent.com/assets/1472728/11319700/c425ac0c-9090-11e5-925d-e0ea5bcd34c6.png">

**Comment by mrodalgaard** [comment]
@akaRem; I like your issue title :smile:, but it is actually meant to look like that.

`/\bTODO:?\d*($|\s.*$)/g` is the [regex](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions) that's used to find your document todos. Try adding a FIXME and you will see the regex for the fixmes search.

If you dislike this layout I can comfort you with that it will change soon, see #85.

**Comment by akaRem** [comment]
@mrodalgaard 
This looks like debug info and feels like foreign thing for standard mode.

**Comment by mrodalgaard** [comment]
New release includes a table where you can set which data should be shown (click the little gear icon).
