### ISSUE TITLE
Live search todos

### ISSUE THREAD

**Issue by mrodalgaard** [mrodalgaard/atom-todo-show#88]
Input field that live filters todos listed in table.

**Comment by ThomasLandauer** [comment]
@mrodalgaard Was this feature lost in recent versions? I see the "Search Todos" input field in your screenshot in `README.md` https://raw.githubusercontent.com/mrodalgaard/atom-todo-show/master/screenshots/preview.png
But I don't see it in my Atom :-( I have version 2.3.2 of the package.

**Comment by mrodalgaard** [comment]
@ThomasLandauer; yes. Unfortunately there was a bug that made a system error on Atom in certain cases, so I had to remove it temporary until I have the time to create a fix. See #198

**Comment by ThomasLandauer** [comment]
For anybody needing the search functionality: https://atom.io/packages/todo supports it
