### ISSUE TITLE
Make the saved .md file look like configured view

### ISSUE THREAD

**Issue by netsi1964** [mrodalgaard/atom-todo-show#89]
Hi,

Love your package - but could you please make the exported `.md` file look like the chosen/configured output inside Atom. So that if I have chosen table view with 3 columns the saved/exported/generated `.md` will also be a table based.

/Sten

**Comment by mrodalgaard** [comment]
I'm not a big fan of markdown tables in general, primarily because they are not very nice/fast to edit. Are you suggesting an option where todos are exported something like this:

```md
| Text  | Type  | File     |
|--------------------------|
| 4 5 6 | TODO  | sample.c |
| 4 5 6 | FIXME | sample.c |
```

Are there any nodejs markdown table generators?

**Comment by netsi1964** [comment]
Yes something like this:

```
| Text  | Type  | File     |
|--------------------------|
| [4 5 6](sample.c) | TODO  | [sample.c](sample.c) |
| [4 5 6](sample.c) | FIXME  | [sample.c](sample.c) |
```

**Comment by mrodalgaard** [comment]
I'm actually okay with implementing this as an option. I just need to figure out how to prompt the user for which output to choose (list vs table).

**Comment by mrodalgaard** [comment]
You can now change the outputted markdown format using the `saveOutputAs` option. Only `List` or `Table` is available at the moment. Let me know how it works out.
