### ISSUE TITLE
Create a MD link to the reffered files in the exported MD file

### ISSUE THREAD

**Issue by netsi1964** [mrodalgaard/atom-todo-show#90]
Hi,

Would be great if you were to generate clickable links to the file with say a TO-DO point.
You know how to do it I guess :-) It will make it possible here on GitHub to click into the issue.

**Comment by mrodalgaard** [comment]
I'm not sure I understand what you mean here. You want the outputtet markdown `File` column to be absolute links to the file (e.g. `[file.txt](file://Users/XXX/Documents/sample.c)`)? This would be a nice feature, but could result in some misunderstanding when sending the markdown todo list to others.

**Comment by netsi1964** [comment]
I would suggest _relative_ links like [file.txt](file.txt)

**Comment by mrodalgaard** [comment]
Relative links would only work when the file is saved to the project root. And as far as I know without the `file://` prefix it wont work at all (github.com does some magic that is not part of the markdown spec to make relative links work).
