### ISSUE TITLE
How can one restrict the to do search for a specific folder or current buffer?

### ISSUE THREAD

**Issue by hugeme** [mrodalgaard/atom-todo-show#91]
First of all thanks for that helpful tool. After installing, it took the package ca. 3 min to search through my computer and show me of 2900 to dos. Is there a way to restrict the search to a specific path or the current buffer?

**Comment by mrodalgaard** [comment]
The package is not really meant to be used to search your whole computer for todos, but more as a per project overview of todos. It searches the Atom windows currently opened project root.

As described in the [readme](https://github.com/mrodalgaard/atom-todo-show/blob/master/README.md#config); `ignoreThesePaths` or your `.gitignore` file can be used to choose which directories the search should ignore (e.g. `node_modules`).

You also have the option to open the todo list by using `Todo Show: Find In Open Files` from the command palette. This will limit the search to currently open files. This option can also be toggled using the top right button inside the todo-show view (labeled `Workspace` in the screenshot).

<img width="569" alt="todo-show-button" src="https://cloud.githubusercontent.com/assets/659763/11768278/0328e8d6-a1c8-11e5-9d66-512c738f2b3a.png">

**Comment by mrodalgaard** [comment]
@hugeme, if this answered your question, please close the ticket.
