### ISSUE TITLE
display the todo count

### ISSUE THREAD

**Issue by Nyalab** [mrodalgaard/atom-todo-show#92]
Hello there,

good work on the plugin, one thing that could be brilliant is to display the number of todos to know on big projects to refactor for instance, an idea of the progress that we are doing

good work though

**Comment by mrodalgaard** [comment]
Great idea. I have thought about adding a todo counter in the status bar, but that requires constantly updating the todos - also when the todo panel is not open. So I might just add it to the panel somewhere subtle.

**Comment by mrodalgaard** [comment]
Will be included in next release

**Comment by Nyalab** [comment]
thank you!
