### ISSUE TITLE
always searchs in Workspace

### ISSUE THREAD

**Issue by toshirov** [mrodalgaard/atom-todo-show#93]
By default, it always opens the panel showing the TODOs of the workspace and I like to show only the open files, every time I open the panel I have to click on workspace button, is there a way to save the last option I've selected when opening the panel?

**Comment by mrodalgaard** [comment]
You can use the command palettes `Show Todo: Find In Open Files` command. This opens the todo panel in `Open Files` mode.

You can use Atom's `keymap.cson` to set a key combination for this command. And I believe you can also overwrite the default command (<kbd>ALT</kbd> + <kbd>SHIFT</kbd> + <kbd>T</kbd>) I bundle with the package.

**Comment by mrodalgaard** [comment]
I am closing this, as it is already possible.
