### ISSUE TITLE
Windows filesystem .gitignore support

### ISSUE THREAD

**Issue by alexpatow** [mrodalgaard/atom-todo-show#94]
Hi, 

I've really enjoyed using your package, however I ran into an issue today. I'm using a window's system and the slashes in the .gitignore file are "/", but the opposite direction ("\") in the filesystem.

In order to prevent todo-show from searching directories, I have to manually add them in the preferences using the windows style ("\") slashes.

My .gitignore is:
node_modules/
platforms/
plugins/
www/

But my Atom preferences are:
www\, node_modules\, plugins\, hooks\, TODO.md

It doesn't work if I copy that into the .gitignore file.

Of course I could just be missing something, but I think this is the cause of my problem.

Please let me know if there's anything else I can do to help.

Thanks,

Alex

**Comment by mrodalgaard** [comment]
This must be something else. I'm using the same module for ignoring paths as find-and-replace which bundles default with Atom. Are the ignored paths working with `Project Find: Show`? I'm afraid I need more info.

Remember that the opened project needs to be under git for the `.gitignore` file to be used.

I just installed git on my Windows machine and everything seems to be working fine with `.gitignore`.

Todo-Show with a todo in `folder/test.txt`:
![capture1](https://cloud.githubusercontent.com/assets/659763/12372964/801509c2-bc69-11e5-9679-7dd893676665.PNG)

After adding the line you mention it is ignored:
![capture3](https://cloud.githubusercontent.com/assets/659763/12372969/b49272ca-bc69-11e5-9f9a-38c9dd2e2593.PNG)

You don't even have to add the ending slash to indicate it's a folder:
![capture4](https://cloud.githubusercontent.com/assets/659763/12372971/c1a18f78-bc69-11e5-88d2-cc514eca9439.PNG)

**Comment by alexpatow** [comment]
Hey, thanks for your help, I've transitioned to a mac computer so I haven't been able to test. I'm going to just assume it was a fluke in my .gitignore or something. I'll close this issue.
