### ISSUE TITLE
Not sorting properly by 'line'

### ISSUE THREAD

**Issue by akrawitz** [mrodalgaard/atom-todo-show#97]
When sorting by 'line', todo-show appears to be sorting alphabetically instead of numerically. E.g.:
12
156
2345
4
87
9
Instead of:
4
9
12
87
156
2345

**Comment by mrodalgaard** [comment]
Thank you. Will be included in next release.

**Comment by akrawitz** [comment]
Thanks for addressing this so quickly, and for creating this package.
